fix: ブックマークの作成APIでのエラーの修正 (#113)
下記のエラーメッセージが表示され、500エラーが返るようになっていました。
これを修正します。

```
[16:53:01.826] ERROR (342007): "tag" is required!
    reqId: "req-1b"
    req: {
      "method": "POST",
      "url": "/api/v2/bookmark",
      "hostname": "localhost:8080",
      "remoteAddress": "::ffff:127.0.0.1",
      "remotePort": 51640
    }
    res: {
      "statusCode": 500
    }
    err: {
      "type": "Error",
      "message": "\"tag\" is required!",
      "stack":
          Error: "tag" is required!
              at anonymous0 (eval at build (/home/ubuntu/vilog/server/dist/index.js:22926:27), <anonymous>:46:37)
              at serialize2 (/home/ubuntu/vilog/server/dist/index.js:16901:16)
              at preSerializationHookEnd (/home/ubuntu/vilog/server/dist/index.js:16620:21)
              at preSerializationHook (/home/ubuntu/vilog/server/dist/index.js:16606:9)
              at Reply.send (/home/ubuntu/vilog/server/dist/index.js:16382:11)
              at /home/ubuntu/vilog/server/dist/index.js:3489:19
      "serialization": {
        "url": "/api/v2/bookmark",
        "method": "POST"
      }
    }
```